

#ifndef _PTT_FUN_H_
#define _PTT_FUN_H_

#define   uchar unsigned char	   // 0-255 single byte, use uchar instead of char
#define   uint unsigned int		   // 0-65536 double bytes use uint instead of int
/************* 16-bit CRC check**************/
extern uchar PTT_IN_DOWN(); // Check PTT Press
extern void PTT_IN_UP(); // Wait for the button to be released

/*****************************************/
#endif